# Generated by Django 2.2.7 on 2019-11-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='assign_date',
            field=models.DateField(verbose_name='date assigned'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(verbose_name='date ordered'),
        ),
    ]
