# Generated by Django 2.2.7 on 2019-11-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20191130_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='container_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='remark',
            field=models.TextField(default=None),
        ),
    ]
