# Generated by Django 2.2.7 on 2019-12-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20191130_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='count_of_today',
            field=models.IntegerField(default=1),
        ),
    ]
